### ISSUE TITLE
Can't pass limit to get_objects

### ISSUE THREAD

**Issue by mikeguy29** [kaisero/fireREST#12]
Great module - thanks. 

I've been using it in my script, but when calling "get_objects" I am unable to pass an increased limit beyond the 100. Obviously I could just call "_url" directly, so you may not consider this an issue, but would be good to use the abstraction of "get_objects" and increase the limit as otherwise it takes ages for something like "applications" which has thousands of objects.

I'm not a massive python expert, but don't think I've missed a way to do this using your code (apologies if I have). For now I've just created a child class in my script and overwritten the value that way.

**Comment by kaisero** [comment]
Glad that the module has been of use to you!
TBH I have thought about implementing what you are asking for but so far I've just been too lazy. I'll release a new version by next week which will include what you are asking for.

kind regards
Oliver
