### ISSUE TITLE
the get_policy method errors out when passing "params"

### ISSUE THREAD

**Issue by sudseh** [kaisero/fireREST#3]
It doesn't seem as if the "expanded" flag is permitted for the get_policy method in api 6.2.3. I have been using the following code block instead:
```
#def get_policy(self, policy_id, policy_type, expanded=False):
def get_policy(self, policy_id, policy_type):
        request = '/policy/{0}/{1}'.format(policy_type, policy_id)
#        params = {
#          'expanded': expanded
#       }
        url = self._url('config', request)
        return self._get(url)
#        return self._get(url, params)
```

**Comment by sudseh** [comment]
Cool cool, thanks!

Cheers,
Sudhir

**Comment by kaisero** [comment]
Looks like this has been fixed upstream. Tested expanded param with FPR 6.4.0.x without any issues, therefore there will be no changes to the function
