### ISSUE TITLE
request for syslogalerts and snmpalerts missing leading slash

### ISSUE THREAD

**Issue by rnwolfe** [kaisero/fireREST#4]
https://github.com/kaisero/fireREST/blob/20881b4f6f0548967342044dee46c2d85a1b9ae8/fireREST.py#L520

https://github.com/kaisero/fireREST/blob/20881b4f6f0548967342044dee46c2d85a1b9ae8/fireREST.py#L525

These request parameters need the leading `/`.

**Comment by kaisero** [comment]
Fixed in f1355571f61bfe8f59db6f4a6e5fe27318a5bf89
