### ISSUE TITLE
updates api doesnt work

### ISSUE THREAD

**Issue by gsin0080** [kaisero/fireREST#46]
FMC version 6.6.1

When I tried to retrieve upgradepackages, it returns 404.

response = fmc.update.upgradepackage.get()

requests.exceptions.HTTPError: 404 Client Error: 404 for url: https://fmc.lab.local/api/fmc_config/v1/domain/{domainUUID}/updates/upgradepackages?limit=1000&expanded=True

In API explorer, the updates APIs doesn't have domain and domainUUID in the path

**Comment by kaisero** [comment]
Thanks for the report. Looks like the Namespace definition is missing in the update.upgradepackage resource. The issue will be fixed in v.1.0.5
