### ISSUE TITLE
wrong var used in get_syslogalert_id_by_name

### ISSUE THREAD

**Issue by rnwolfe** [kaisero/fireREST#5]
A problem with the same function referenced in #4; however, this seems to have been resolved in `develop` and not in `master` through the re-working of the function.

In `master`, this line should reference `payload['id']` and not `item['id']`.

https://github.com/kaisero/fireREST/blob/816ecfde7ae1fbfd75aeef56449c02fe6e423d40/__init__.py#L353

**Comment by kaisero** [comment]
Thanks for the report. At some point last year I fixed this and pushed it to master, but failed to update this issue. Closing now.
