### ISSUE TITLE
Unable to perform GET on full list of continent objects

### ISSUE THREAD

**Issue by netman2048** [kaisero/fireREST#60]
Trying to do an fmc.object.continent.get() to get the full list of continents however it fails because the PATH in the Continent object is incorrect.  The URL has continent as plural.

fireREST code

```
from fireREST.fmc import Resource


class Continent(Resource):
    PATH = '/object/continent/{uuid}'
    MINIMUM_VERSION_REQUIRED_GET = '6.1.0'
```

Corrected code

```
from fireREST.fmc import Resource


class Continent(Resource):
    PATH = '/object/continents/{uuid}'
    MINIMUM_VERSION_REQUIRED_GET = '6.1.0'
```

I tested this change and it pulled the continents fine.

**Comment by kaisero** [comment]
Thank you for reporting this issue - I've been a bit busy in the last few months. v1.0.10 will fix this problem
