### ISSUE TITLE
Is there a requirement for a Generated Token Prior to Authentication to an FMC 

### ISSUE THREAD

**Issue by PsionTheory** [kaisero/fireREST#69]
Here's the read out i get when trying an authorized admin developer login. Version 7.0.1 of FMC and FTD 4125
![image](https://user-images.githubusercontent.com/3756590/160229390-ebeacb44-c138-43bf-80f2-d8a5cac56537.png)

**Comment by PsionTheory** [comment]
Hi Submit this may be an issue requiring some type of API privilege setting of some type.  I got basically the same error message when trying this action on a dcloud firewall instance. 

![image](https://user-images.githubusercontent.com/3756590/160251118-d2862208-4f8c-4468-9e44-74ba6b72b7d6.png)

![image](https://user-images.githubusercontent.com/3756590/160251128-76165cf6-e20e-41c9-8bb5-773ff3288365.png)

**Comment by kaisero** [comment]
As explained in the other issue, this was due to trying to connect directly to the NGFW and not FMC
